stages:
    - test
    - update

update_flutter:
  stage: update
  image: "cirrusci/flutter:latest"
  only:
    - main
  tags:
    - flutter_runner
  script:
    - flutter upgrade
    - flutter clean
    - flutter pub get
  interruptible: true

code_quality:
  stage: test
  image: "cirrusci/flutter:latest"
  only: 
    - main
  tags:
    - flutter_runner
  before_script:
    - pub global activate dart_code_metrics
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
  script:
    - metrics lib -r codeclimate  > gl-code-quality-report.json
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

widget_test:
  stage: test
  image: "cirrusci/flutter:latest"
  only:
    - main
  tags:
    - flutter_runner
  script:
    - flutter test test/widget_test
  coverage: '/lines\.*: \d+\.\d+\%/'
  artifacts:
    name: coverage
    paths:
      - $CI_PROJECT_DIR/coverage
