stages:
  - update
  - test
  - build

default:
  image: "cirrusci/flutter:latest"

update_flutter:
  stage: update
  script:
    - flutter clean
    - flutter pub get
  interruptible: true
  only:
    - main

unit_test:
  stage: test
  script:
    - flutter test test/unit_test
  interruptible: true
  only:
    - main

widget_test:
  stage: test
  script:
    - flutter test test/widget_test
  interruptible: true
  only:
    - main

code_quality:
  stage: test
  before_script:
    - dart pub get
    - dart pub global activate dart_code_metrics
  script:
    - mkdir reports
    - dart pub global run dart_code_metrics:metrics analyze lib -r gitlab > reports/code-quality-report.json
  artifacts:
    reports:
      codequality: reports/code-quality-report.json
    paths:
      - reports/
  only:
    - main

android_build:
  stage: build
  script:
    - flutter build apk
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-release.apk
  only:
    - main
