stages:
  - update
  - test
  - build
  - deploy

default:
  image: "cirrusci/flutter:latest"

update_flutter:
  stage: update
  script:
    - flutter clean
    - flutter pub get
  interruptible: true

unit_test:
  stage: test
  script:
    - flutter test test/unit_test
  interruptible: true

widget_test:
  stage: test
  script:
    - flutter test test/widget_test
  interruptible: true

code_quality:
  stage: test
  before_script:
    - dart pub get
    - dart pub global activate dart_code_metrics
  script:
    - mkdir reports
    - dart pub global run dart_code_metrics:metrics analyze lib -r gitlab > reports/code-quality-report.json
  artifacts:
    reports:
      codequality: reports/code-quality-report.json
    paths:
      - reports/

android_build:
  stage: build
  script:
    - flutter build apk
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-release.apk
  interruptible: true

deploy_android_for_testing:
  stage: deploy
  dependencies: [android_build]
  script:
    - sudo apt install npm nodejs
    - npm install -g firebase-tools
    - firebase appdistribution:distribute build/app/outputs/apk/release/app-release.apk --app $FIREBASE_APP_ID --release-notes-files release-notes.txt --groups "androidTesters" --token "$FIREBASE_CI_TOKEN"
  only:
    - main