stages:
  - update
  - test

default:
  image: "cirrusci/flutter:latest"

update_flutter:
  stage: update
  script:
    - flutter clean
    - flutter pub get
  interruptible: true

code_quality:
  stage: test
  before_script:
    - flutter pub global activate dart_code_metrics
  script:
    - flutter pub global run dart_code_metrcis:metrics analyze lib -r gitlab > code-quality-report.json
  artifacts:
    reports:
      codequality: code-quality-report.json

unit_test:
  stage: test
  script:
    - flutter test test/unit_test
  interruptible: true

widget_test:
  stage: test
  script:
    - flutter test test/widget_test
  interruptible: true
