stages:
  - update
  - test

default:
  image: "cirrusci/flutter:latest"

update_flutter:
  stage: update
  tags:
    - flutter_runner_windows
  script:
    - flutter clean
    - flutter pub get
  interruptible: true

code_quality:
  stage: test
  tags:
    - flutter_runner_windows
  before_script:
    - pub global activate dart_code_metrics
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
  script:
    - metrics lib -r codeclimate  > gl-code-quality-report.json
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

widget_test:
  stage: test
  tags:
    - flutter_runner_windows
  script:
    - flutter test test/widget_test
