# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Flutter.gitlab-ci.yml

stages:
    - test
    - update

update_flutter:
  stage: update
  image: "cirrusci/flutter:latest"
  only:
    - master
  tags:
    - flutter
  script:
    - flutter upgrade
    - flutter clean
    - flutter pub get
  interruptible: true

code_quality:
  stage: test
  image: "cirrusci/flutter:latest"
  only: 
    - master
  tags:
    - flutter
  before_script:
    - pub global activate dart_code_metrics
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
  script:
    - metrics lib -r codeclimate  > gl-code-quality-report.json
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

widget_test:
  stage: test
  image: "cirrusci/flutter:latest"
  only:
    - master
  tags:
    - flutter
  script:
    - flutter test test/widget_test
  coverage: '/lines\.*: \d+\.\d+\%/'
  artifacts:
    name: coverage
    paths:
      - $CI_PROJECT_DIR/coverage
